flags: {}
packages:
- .
extra-deps:
- fixed-list-0.1.6
- predicate-class-0.1.0.1
- git: https://github.com/uber/queryparser.git
  commit: 6015e8f273f4498326fec0315ac5580d7036f8a4
  subdirs:
  - .
  - dialects/vertica
resolver: lts-10.4
