version: 2.0

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and tag the image
          command: docker build . -t $DOCKER_REPO:$(git describe) -t $DOCKER_REPO:latest
      - run:
          name: Push the image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push $DOCKER_REPO:$(git describe)
              docker push $DOCKER_REPO:latest
            fi
